services:
  nosana-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Frontend (http-server)
      - "8080:8080"  # Backend API (Mastra)
    environment:
      - NODE_ENV=production
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const req = http.request({hostname:'localhost',port:8080,path:'/',timeout:5000}, (res) => process.exit(res.statusCode < 400 ? 0 : 1)); req.on('error', () => process.exit(1)); req.end();"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - nosana-network

networks:
  nosana-network:
    driver: bridge
